### ISSUE TITLE
Runtime Error - Update SSLZE

### ISSUE THREAD

**Issue by ptd-tbs** [cds-snc/tracker#47]
Following issue occurs:

File "/opt/apps/tracker/.venv/lib/python3.6/site-packages/nassl/ssl_client.py", line 165, in set_underlying_socket
    raise RuntimeError('A socket was already set')
RuntimeError: A socket was already set

Proposed resolution is update the SSLYZE component.

**Comment by buckley-w-david** [comment]
According to https://github.com/nabla-c0d3/sslyze/issues/319 updating to a version after 2.0.0 should resolve the issue.

However that update is already in the most recent domain-scan (which is what actually uses sslyze), and was added around the beginning of September.

If the most recent version of domain-scan is pulled, you should also get the most recent version of sslyze.

**Comment by obrien-j** [comment]
Was chatting with @konklone about it earlier. They haven't yet deployed the new version.

We'll want to pull in https://github.com/18F/domain-scan/commit/f72964e98678e9b048f53d62a2460916f0c65359 as well.

**Comment by sayaHub** [comment]
Hey John,

I just noticed that when CircleCI is building the tar file for tracker ,  the deployment script (
https://github.com/cds-snc/tracker/blob/master/deploy/build-env.sh) have this

line : mkdir -p domain-scan && wget -q -O - https://api.github.com/repos/18F/domain-scan/tarball | tar xz --strip-components=1 -C domain-scan

Is that your own tarball that you guys created from your repo ((https://github.com/cds-snc/domain-scan) ?

**Comment by sayaHub** [comment]
since we are using 18F domain scan repo for the Tracker build, the  18F/domain-scan@f72964e is already included in the Tracker build.
